version: 2.1

commands:
  run-test:
    steps:
      - checkout
      - restore_cache:
          name: Restore Dependency Cache
          keys:
            - v1-dependency-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CIRCLE_JOB }}
            - v1-dependency-cache-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Create Dependency Cache
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - ./node_modules
      - run:
          name: Lint Source
          command: npm run lint --if-present
      - run:
          name: Build Source
          command: npm run build --if-present

jobs:
  node-current:
    docker:
      - image: cimg/node:current
    steps:
      - run-test

  node-lts:
    docker:
      - image: cimg/node:lts
    steps:
      - run-test

workflows:
  node-run-tests:
    jobs:
      - node-current
      - node-lts
  version: 2
